# Generated by Django 5.2.7 on 2025-10-10 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id_tramite', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tiempo_estimado', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id_requisito_tramite', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('archivo_requerido', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['orden'],
            },
        ),
    ]
