# Generated by Django 5.2.7 on 2025-10-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisito',
            table='requisito',
        ),
        migrations.AlterModelTable(
            name='tramite',
            table='tramite',
        ),
    ]
