# Generated by Django 5.2.7 on 2025-10-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('tramites', '0002_alter_requisito_table_alter_tramite_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='costo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
