# Generated by Django 5.2.7 on 2025-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('tramites', '0003_tramite_departamento_alter_tramite_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='departamento',
        ),
        migrations.AddField(
            model_name='tramite',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='tramites', to='departamentos.departamento'),
        ),
    ]
