# Generated by Django 5.2.7 on 2025-10-23 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('INTERNO', 'Comprobante Interno')], max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comprobante Contable',
                'verbose_name_plural': 'Comprobantes Contables',
                'db_table': 'comprobante',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionContable',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='REGISTRADO', max_length=20)),
            ],
            options={
                'verbose_name': 'Transacción Contable',
                'verbose_name_plural': 'Transacciones Contables',
                'db_table': 'transaccion_contable',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id_cuenta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'cuenta_contable',
                'ordering': ['codigo'],
            },
        ),
    ]
