# Generated by Django 5.2.7 on 2025-10-23 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('pagos', '0001_initial'),
        ('urbanizaciones', '0011_alter_verticeurbanizacion_este_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncontable',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='pagos.pago'),
        ),
        migrations.AddField(
            model_name='transaccioncontable',
            name='urbanizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='urbanizaciones.urbanizacion'),
        ),
        migrations.AddField(
            model_name='transaccioncontable',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
