# Generated by Django 5.2.7 on 2025-10-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0002_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncontable',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='contabilidad.transaccioncontable'),
        ),
    ]
