# Generated by Django 5.2.7 on 2025-10-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='permite_financiamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
