# Generated by Django 5.2.7 on 2025-10-12 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_vivienda_permite_financiamiento_vivienda_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viviendas_compradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
