# Generated by Django 5.2.7 on 2025-10-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_vivienda_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie construida en m²', max_digits=8, null=True),
        ),
    ]
