# Generated by Django 5.2.7 on 2025-10-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0004_vivienda_superficie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viviendaimagen',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
