# Generated by Django 5.2.7 on 2025-10-15 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0005_alter_viviendaimagen_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaVivienda',
            fields=[
                ('id_caracteristica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Característica de Vivienda',
                'verbose_name_plural': 'Características de Viviendas',
                'db_table': 'caracteristica_vivienda',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
