# Generated by Django 5.2.7 on 2025-10-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0006_caracteristicavivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicavivienda',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
