# Generated by Django 5.2.7 on 2025-10-23 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(help_text='Usuario que actúa como cliente', limit_choices_to={'rol__nombre': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(blank=True, help_text='Empleado responsable de supervisar todo el proceso', limit_choices_to={'rol__nombre__in': ['ADMINISTRATIVO', 'ARQUITECTO', 'TOPOGRAFO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_encargados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('ATRASADA', 'Atrasada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField(default=1, help_text='1 = baja, 5 = alta')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='procesos.proceso')),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre__in': ['ADMINISTRATIVO', 'ARQUITECTO', 'TOPOGRAFO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
