# Generated by Django 5.2.7 on 2025-10-31 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
        ('urbanizaciones', '0011_alter_verticeurbanizacion_este_x_and_more'),
        ('viviendas', '0007_caracteristicavivienda_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Proceso', 'verbose_name_plural': 'Procesos'},
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='fecha_inicio',
            new_name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proceso',
            name='documentos',
            field=models.JSONField(blank=True, help_text='Archivos subidos por el usuario, referenciados por tipo y nombre', null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='id_proceso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='urbanizaciones.lote'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales del proceso', null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='requisitos',
            field=models.JSONField(blank=True, help_text='Listado de requisitos y documentos requeridos', null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proceso',
            name='vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='viviendas.vivienda'),
        ),
        migrations.AlterModelTable(
            name='proceso',
            table='proceso',
        ),
        migrations.CreateModel(
            name='ProcesoInterno',
            fields=[
                ('id_proceso_interno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsables', models.ManyToManyField(blank=True, related_name='procesos_internos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso Interno',
                'verbose_name_plural': 'Procesos Internos',
                'db_table': 'proceso_interno',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='proceso_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='procesos.procesointerno'),
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
