# Generated by Django 5.2.7 on 2025-11-01 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_alter_proceso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoProcesoInterno',
            fields=[
                ('id_paso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número de orden del paso')),
                ('titulo', models.CharField(max_length=200)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='procesos.procesointerno')),
            ],
            options={
                'verbose_name': 'Paso del Proceso',
                'verbose_name_plural': 'Pasos del Proceso',
                'db_table': 'paso_proceso',
                'ordering': ['orden'],
            },
        ),
    ]
