# Generated by Django 5.2.7 on 2025-11-02 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id_importacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_importacion', models.CharField(blank=True, choices=[('materiales', 'Materiales de construcción'), ('maquinaria', 'Maquinaria y equipos'), ('equipos_hvac', 'Equipos HVAC y eléctricos'), ('acabados', 'Acabados e interiorismo'), ('herramientas', 'Herramientas y suministros menores'), ('otros', 'Otros')], help_text='Seleccione el tipo de importación', max_length=50, null=True)),
                ('servicios_asociados', models.TextField(blank=True, null=True)),
                ('proveedores', models.TextField(blank=True, null=True)),
                ('proceso_trabajo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
