# Generated by Django 5.2.7 on 2025-10-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_rol',
            new_name='id_usuario',
        ),
    ]
