# Generated by Django 5.2.7 on 2025-10-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_rol_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='foto',
            new_name='foto_url',
        ),
    ]
