# Generated by Django 5.2.7 on 2025-10-27 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0003_tramite_departamento_alter_tramite_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_url', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.requisito')),
            ],
            options={
                'verbose_name': 'Documento de Usuario',
                'verbose_name_plural': 'Documentos de Usuario',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil_url', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documentos', models.ManyToManyField(blank=True, through='perfiles.DocumentoUsuario', to='tramites.requisito')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_usuario', to='perfiles.perfil'),
        ),
    ]
