# Generated by Django 5.2.7 on 2025-11-02 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id_consultoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('servicios_especializados', models.TextField(blank=True, null=True)),
                ('proceso_trabajo', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultoría',
                'verbose_name_plural': 'Consultorías',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
