# Generated by Django 5.2.7 on 2025-11-02 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedCORS',
            fields=[
                ('id_redcors', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(help_text='Nombre del proyecto o área donde se realiza el servicio', max_length=150)),
                ('tipo_servicio', models.CharField(choices=[('conexion', 'Conexión de Red'), ('mantenimiento', 'Mantenimiento de Infraestructura'), ('optimización', 'Optimización de Red'), ('seguridad', 'Seguridad y Monitoreo'), ('soporte', 'Soporte Técnico')], max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del servicio realizado')),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor o empresa encargada del servicio', max_length=150)),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones adicionales')),
            ],
            options={
                'verbose_name': 'Red CORS',
                'verbose_name_plural': 'Redes CORS',
                'ordering': ['-fecha_realizacion'],
            },
        ),
    ]
