# Generated by Django 5.2.7 on 2025-11-02 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redcors',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Red CORS', 'verbose_name_plural': 'Redes CORS'},
        ),
        migrations.RemoveField(
            model_name='redcors',
            name='fecha_realizacion',
        ),
        migrations.AddField(
            model_name='redcors',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
