# Generated by Django 5.2.7 on 2025-10-11 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urbanizacion',
            fields=[
                ('id_urbanizacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('planimetria_pdf', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urbanizaciones', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Urbanizacion',
                'verbose_name_plural': 'Urbanizaciones',
                'db_table': 'urbanizacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_CREDITO', 'En Crédito'), ('OCUPADO', 'Ocupado')], default='DISPONIBLE', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_comprados', to=settings.AUTH_USER_MODEL)),
                ('urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='urbanizaciones.urbanizacion')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lote',
                'ordering': ['nombre'],
            },
        ),
    ]
