# Generated by Django 5.2.7 on 2025-10-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0002_urbanizacion_portada_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanizacion',
            name='estado',
        ),
    ]
