# Generated by Django 5.2.7 on 2025-10-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0003_remove_urbanizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanizacion',
            name='planimetria_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
