# Generated by Django 5.2.7 on 2025-10-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0004_urbanizacion_planimetria_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanizacion',
            name='planimetria_texto',
        ),
    ]
