# Generated by Django 5.2.7 on 2025-10-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0005_remove_urbanizacion_planimetria_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanizacion',
            name='area_total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='urbanizacion',
            name='total_lotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='urbanizacion',
            name='total_manzanas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
