# Generated by Django 5.2.7 on 2025-10-13 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0006_urbanizacion_area_total_urbanizacion_total_lotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='urbanizacion',
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id_manzana', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('este_x', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('norte_y', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('urbanizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='urbanizaciones.urbanizacion')),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
                'db_table': 'manzana',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='urbanizaciones.manzana'),
        ),
    ]
