# Generated by Django 5.2.7 on 2025-10-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0007_remove_lote_urbanizacion_manzana_lote_manzana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='manzana',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='urbanizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='urbanizaciones.urbanizacion'),
        ),
        migrations.DeleteModel(
            name='Manzana',
        ),
    ]
