# Generated by Django 5.2.7 on 2025-10-13 02:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0008_alter_lote_manzana_lote_urbanizacion_delete_manzana'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticeUrbanizacion',
            fields=[
                ('id_vertices_urbanizacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('este_x', models.DecimalField(decimal_places=6, max_digits=12)),
                ('norte_y', models.DecimalField(decimal_places=6, max_digits=12)),
                ('orden', models.CharField(max_length=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='urbanizaciones.urbanizacion')),
            ],
            options={
                'verbose_name': 'Vértices de la Urbanización',
                'verbose_name_plural': 'Vértices de las Urbanizaciones',
                'db_table': 'vertices_urbanizacion',
                'ordering': ['orden'],
            },
        ),
    ]
