# Generated by Django 5.2.7 on 2025-10-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0009_verticeurbanizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='coordenadas',
        ),
    ]
