# Generated by Django 5.2.7 on 2025-10-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizaciones', '0010_remove_lote_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verticeurbanizacion',
            name='este_x',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='verticeurbanizacion',
            name='norte_y',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
