# Generated by Django 5.2.7 on 2025-10-23 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urbanizaciones', '0011_alter_verticeurbanizacion_este_x_and_more'),
        ('viviendas', '0007_caracteristicavivienda_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(choices=[('CONTADO', 'Venta al Contado'), ('CREDITO', 'Venta a Crédito'), ('FINANCIAMIENTO', 'Venta con Financiamiento Mixto')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cuotas', models.PositiveIntegerField(default=0)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de interés anual (%)', max_digits=5)),
                ('banco_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('empresa_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='urbanizaciones.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
