# Generated by Django 5.2.7 on 2025-10-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('CONTADO', 'Venta al Contado'), ('CREDITO', 'Venta a Crédito'), ('FINANCIAMIENTO', 'Venta con Financiamiento')], max_length=20),
        ),
    ]
